[package]
name = "termcolor_output"
version = "0.1.0"
authors = ["Cerberuser"]
edition = "2018"

[dependencies]
termcolor_output_impl = { path = "../termcolor_output_impl" }

[dev-dependencies]
trybuild = "1.0"
