[package]
name = "termcolor_output"
version = "1.0.0-rc.1"
authors = ["Cerberuser"]
edition = "2018"

[dependencies]
termcolor_output_impl = { path = "../derive" }
termcolor = "1.0"

[dev-dependencies]
trybuild = "1.0"
